In [1]:
# Import the libraries
import numpy as np
import pandas as pd
from scipy.stats import skew

In [2]:
# Load the dataset
df = pd.read_csv('../data/life_expectancy_data.csv')

# Check the first few rows of the dataset
df.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [3]:
# Initial inspection
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Country                          2938 non-null   str
 1   Year                             2938 non-null   int64
 2   Status                           2938 non-null   str
 3   Life expectancy                  2928 non-null   float64
 4   Adult Mortality                  2928 non-null   float64
 5   infant deaths                    2938 non-null   int64
 6   Alcohol                          2744 non-null   float64
 7   percentage expenditure           2938 non-null   float64
 8   Hepatitis B                      2385 non-null   float64
 9   Measles                          2938 non-null   int64
 10   BMI                             2904 non-null   float64
 11  under-five deaths                2938 non-null   int64
 12  Polio                            2919 non-null   float64
 13  Total expenditure                2712 non-null   float64
 14  Diphtheria                       2919 non-null   float64
 15   HIV/AIDS                        2938 non-null   float64
 16  GDP                              2490 non-null   float64
 17  Population                       2286 non-null   float64
 18   thinness  1-19 years            2904 non-null   float64
 19   thinness 5-9 years              2904 non-null   float64
 20  Income composition of resources  2771 non-null   float64
 21  Schooling                        2775 non-null   float64
dtypes: float64(16), int64(4), str(2)
memory usage: 505.1 KB

In [4]:
df.describe()

,Year,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
count,2938.000000,2928.000000,2928.000000,2938.000000,2744.000000,2938.000000,2385.000000,2938.000000,2904.000000,2938.000000,2919.000000,2712.00000,2919.000000,2938.000000,2490.000000,2.286000e+03,2904.000000,2904.000000,2771.000000,2775.000000
mean,2007.518720,69.224932,164.796448,30.303948,4.602861,738.251295,80.940461,2419.592240,38.321247,42.035739,82.550188,5.93819,82.324084,1.742103,7483.158469,1.275338e+07,4.839704,4.870317,0.627551,11.992793
std,4.613841,9.523867,124.292079,117.926501,4.052413,1987.914858,25.070016,11467.272489,20.044034,160.445548,23.428046,2.49832,23.716912,5.077785,14270.169342,6.101210e+07,4.420195,4.508882,0.210904,3.358920
min,2000.000000,36.300000,1.000000,0.000000,0.010000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,0.37000,2.000000,0.100000,1.681350,3.400000e+01,0.100000,0.100000,0.000000,0.000000
25%,2004.000000,63.100000,74.000000,0.000000,0.877500,4.685343,77.000000,0.000000,19.300000,0.000000,78.000000,4.26000,78.000000,0.100000,463.935626,1.957932e+05,1.600000,1.500000,0.493000,10.100000
50%,2008.000000,72.100000,144.000000,3.000000,3.755000,64.912906,92.000000,17.000000,43.500000,4.000000,93.000000,5.75500,93.000000,0.100000,1766.947595,1.386542e+06,3.300000,3.300000,0.677000,12.300000
75%,2012.000000,75.700000,228.000000,22.000000,7.702500,441.534144,97.000000,360.250000,56.200000,28.000000,97.000000,7.49250,97.000000,0.800000,5910.806335,7.420359e+06,7.200000,7.200000,0.779000,14.300000
max,2015.000000,89.000000,723.000000,1800.000000,17.870000,19479.911610,99.000000,212183.000000,87.300000,2500.000000,99.000000,17.60000,99.000000,50.600000,119172.741800,1.293859e+09,27.700000,28.600000,0.948000,20.700000

In [5]:
df.isnull().sum()

Country                              0
Year                                 0
Status                               0
Life expectancy                     10
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
percentage expenditure               0
Hepatitis B                        553
Measles                              0
 BMI                                34
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
 HIV/AIDS                            0
GDP                                448
Population                         652
 thinness  1-19 years               34
 thinness 5-9 years                 34
Income composition of resources    167
Schooling                          163
dtype: int64

In [6]:
# Standardize columns names 
df.columns = [col.strip().replace(' ', '_').lower() for col in df.columns]
print(df.columns.tolist())

['country', 'year', 'status', 'life_expectancy', 'adult_mortality', 'infant_deaths', 'alcohol', 'percentage_expenditure', 'hepatitis_b', 'measles', 'bmi', 'under-five_deaths', 'polio', 'total_expenditure', 'diphtheria', 'hiv/aids', 'gdp', 'population', 'thinness__1-19_years', 'thinness_5-9_years', 'income_composition_of_resources', 'schooling']

In [7]:
# Find duplicate rows
df.duplicated().sum()

np.int64(0)

In [8]:
# Converting 'status' col into numerical
print(df['status'].unique())

df['status'] = df['status'].map({'Developing': 0, 'Developed': 1})

print(df['status'].unique())

<StringArray>
['Developing', 'Developed']
Length: 2, dtype: str
[0 1]

In [9]:
# Check missing values per rows with more than 90 percent missing
(df.drop(['country', 'year', 'status'], axis = 1).isnull().mean(axis = 1) > 0.9).sum()

np.int64(0)

In [10]:
# Sort the data for time-based operations
df = df.sort_values(['country', 'year']).reset_index(drop = True)

In [11]:
# Check if missing values have a meaning or just random
df.groupby(df['gdp'].isnull().astype(int))['life_expectancy'].mean()

gdp
0    69.370664
1    68.407449
Name: life_expectancy, dtype: float64

In [12]:
# Drop the missing values in Life expectancy due to it being our target
df = df.dropna(subset = ['life_expectancy'])

In [13]:
# Fill missing values based on the skew 
feature_cols = [
    'adult_mortality', 'infant_deaths', 'alcohol', 'percentage_expenditure',
    'hepatitis_b', 'measles', 'bmi', 'under-five_deaths', 'polio',
    'total_expenditure', 'diphtheria', 'hiv/aids', 'gdp', 'population',
    'thinness__1-19_years', 'thinness_5-9_years',
    'income_composition_of_resources', 'schooling'
]

method = {}
for col in feature_cols:
    col_data = df[col].dropna()
    if len(col_data) > 0:
        sk = skew(col_data)
        # If it is less, we have to mean
        method[col] = abs(sk) >= 1
    else:
        # Default it is going to median
        method[col] = True 

# Display the methods
for key, value in method.items():
    if ~value:
        print(f'{key}: {value}')

alcohol: False
bmi: False
total_expenditure: False
schooling: False

We are going to use mean for the values above.

In [14]:
# Fill based on country, status, and global
country_stats = {}
status_stats = {}
global_stats = {}

for col in feature_cols:
    agg_func = 'median' if method[col] else 'mean'

    global_stats[col] = df[col].agg(agg_func)

    status_stats[col] = df.groupby('status')[col].agg(agg_func)

    country_stats[col] = df.groupby('country')[col].agg(agg_func)

# Apply imputation 
for col in feature_cols:
    # 1. Fill with country 
    df[col] = df[col].fillna(
        df['country'].map(country_stats[col])
    )
    # 2. Fill remaining with status
    df[col] = df[col].fillna(
        df['status'].map(status_stats[col])
    )
    # 3. Fill any still remaining with global stat
    df[col] = df[col].fillna(global_stats[col])

df[feature_cols].isnull().sum().sum()

np.int64(0)

In [15]:
# IQR func to detect outliers
def detect_outliers_iqr(df, columns = None):
    '''
    Returns a boolean DataFrame of the same shape, where True marks outliers 
    (values outside [Q1 - 1.5*IQR, Q3 + 1.5*IQR]).
    
    Parameters
    ----------
    df : pandas DataFrame
    columns : list of str, optional
        Columns to check. If None, all numeric columns are used.
    
    Returns
    -------
    pandas DataFrame (boolean)
    '''
    if columns is None:
        columns = df.select_dtypes(include = 'number').columns

    outlier_mask = pd.DataFrame(False, index = df.index, columns = df.columns)

    for col in columns:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower = Q1 - (1.5 * IQR)
        upper = Q3 + (1.5 * IQR)
        outlier_mask[col] = (df[col] < lower) | (df[col] > upper)

    return outlier_mask

In [16]:
# Detect outliers
outlier_flag = detect_outliers_iqr(df, columns = feature_cols)

# Count the outliers
outlier_counts = outlier_flag.sum().sort_values(ascending = False)
print(outlier_counts[outlier_counts > 0])

hiv/aids                           542
measles                            542
gdp                                459
population                         452
under-five_deaths                  394
percentage_expenditure             388
infant_deaths                      315
diphtheria                         308
hepatitis_b                        293
polio                              278
income_composition_of_resources    130
thinness__1-19_years               100
thinness_5-9_years                  99
adult_mortality                     82
schooling                           59
total_expenditure                   34
alcohol                              1
dtype: int64

In [17]:
# Save the cleaned dataset
# Commented to avoid repetitions
# df.to_csv('../data/life_expectancy_data_cleaned.csv', index = False)